baseURL = "http://awurster.com/"
languageCode = "en-us"
title = "awurster[.]com"
theme = "pulp"

[Author]
    name = "Andrew"

[params]
    [params.colors]
        background = "#383838"
        foreground = "#dedede"
        hover = "#ffffff"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/awurster"

    [[params.links]]
        icon = "linkedin"
        title = "Linkedin"
        url = "https://www.linkedin.com/in/andrew-w-46814818/"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:contact@awurster.com"

[deployment]

    [[deployment.targets]]
    # An arbitrary name for this target.
    name = "s3-static-www-awurster-com"
    # S3; see https://gocloud.dev/howto/blob/#s3
    URL = "s3://www.awurster.com?region=eu-central-1"

    [[deployment.matchers]]
    # Cache static assets for 20 years.
    pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
    cacheControl = "max-age=630720000, no-transform, public"
    gzip = true

    [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true