baseURL = "https://awurster.com/"
languageCode = "en-us"
title = "awurster[.]com"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true


[params]
    author = "@awurster"
    avatar = "portrait.jpg"
    favicon = "favicon.ico"
    description = """
        Welcome.
        Thanks for dropping by.
    """

    [params.colors]
        background = "#383838"
        foreground = "#dedede"
        hover = "#ffffff"

[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/yourciscokid"
    weight = 10

[[menu.main]]
    identifier = "linkedin"
    # name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/andrew-w-46814818/"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/awurster"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:contact@awurster.com"
    weight = 40




[deployment]

    [[deployment.targets]]
    # An arbitrary name for this target.
    name = "s3-static-www-awurster-com"
    # S3; see https://gocloud.dev/howto/blob/#s3
    URL = "s3://www.awurster.com?region=eu-central-1"

    [[deployment.matchers]]
    # Cache static assets for 20 years.
    pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
    cacheControl = "max-age=630720000, no-transform, public"
    gzip = true

    [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true