name: Hugo S3

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main
          
      - name: Deploy site to S3
        uses: plopcas/hugo-s3-action@v1.3.0
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MINIFY: 'true'